someengineering/resoto-ui

- src/components/terminal/component_terminal.gd
- src/project.godot
- src/scripts/autoloads/saveload_settings.gd
- src/scripts/ui_main.gd
- Automatic UI scaling by client dpi (educated guess) when no settings file is found
**Fixed minor usability issues with the terminal**
- CTRL+C clears line and adds old command line content greyed out to the terminal
- If there was no content in the command line, ^C will be added to the terminal
- No defocusing when copying content in the terminal
- Mac Command key was added to the modifier keys
> Usability improvements of the terminal and ui scale

- src/components/dashboard/new_widget_popup/new_widget_popup.gd
- src/components/dashboard/new_widget_popup/new_widget_popup.tscn
The code was using the same event a context of new datasources.
> Fix wrong event and context when creating new datasource from template

- src/components/dashboard/new_widget_popup/new_widget_popup.gd
Fixes a bug that, When creating a widget with maximum 1 datasource, and then trying to create another, the "New¨ datasource button and related fields remained invisible.
> Fix bug that caused the new datasource fields to be invisible sometimes

- src/scripts/classes/utils.gd
This caused in the date range selection to show e.g "Nov¨ but the date actually being October.
> Fix offset by one in the month array

- src/components/dashboard/container/widget_container.gd
- src/components/dashboard/container/widget_container.tscn
- src/components/dashboard/new_widget_popup/data_source_container.gd
- src/components/dashboard/new_widget_popup/data_source_container.tscn
- src/components/dashboard/new_widget_popup/new_widget_popup.gd
There were some data sources kept alive in the back that should have been freed. 
This also caused bugs that under some circumstances, they would query and fail because the widget that they had assigned (specifically the preview widget in the add widget dialog) was freed before.
> Delete datasources when the widget or the data source container that holds its reference is deleted

- Dockerfile
This now creates the git-commit.HEAD file, which contains the long sha of the current git commit, inside the directory which is later copied into the Resoto Docker container.
> [docker][fix] create git-commit file in ui directory

- .github/workflows/test-export.yml
- Dockerfile
Currently the hash is only available in the docker image. This includes it in the uploaded UI as well and also creates the same file for test exports.
> [docker][fix] Create git-commit file before upload

- src/components/dashboard/widget_chart/widget_chart.tscn
Small change to show the grid above the line charts. 
Without this change, it looks like this:
(Note how the grid is only visible behind the top most lines)
With the change, it will look like this:
> Show grid above lines

- src/components/shared/combo_box.gd
This PR fixes this bugs:
- When writing an option that is not listed, the popup panel kept disappearing and appearing very fast instead of just being hidden
- Options popup panel was not being resized according to matching items, but to complete items list instead (so it was always bigger than needed)
- When clearing all the text, all items were available in the popup, the popup didn't resize correctly (introduced when fixing previous item)
> Fix some combo-boxes bugs

- src/components/terminal/component_terminal.gd
Implements two counters (for lines and chunks), and if one of them get to the max setting, it will write to console.
This is to avoid constant slow down in the ui, so we have the slow part spread over the time.
> Write search result in console in chunks to avoid slow down

- src/html_shell/godot.html
- src/scripts/tools/html_helpers.gd
The JS watchdog was started with loading the page, if the UI wasm loaded longer than the 3s of the watchdog, the user would get an unresponsive alert before the UI could even start.
> Start Watchdog on ready

- src/html_shell/godot.html
When the window lost focus, godot was not updating the watchdog alert (because the thread freezes when the tab is not in focus). This lead to a bug where you would always get a watchdog alert on refocus.
> Fix watchdog alert on refocus

- src/components/dashboard/data_sources/data_source_text_search.gd
- src/components/dashboard/new_widget_popup/data_source_container.gd
- src/components/dashboard/new_widget_popup/data_source_container.tscn
- src/components/dashboard/new_widget_popup/new_widget_popup.gd
- src/components/dashboard/widget_table/widget_table.gd
This PR changes how the tables are filled up. Code may be a bit more complex than before, but is more performant, and what is most important, now we font get memory pool issues for large search queries.
Before this PR, when a request was done, the datasource called the `set_data` function on the table. In there, the data was arranged into a Matrix (array of array) which was used to fill the table. This Array needed too many allocations to be filled in large searches and made Godot run out of memory allocation pools.
Right now, the table keeps the data as the request sent it. At the moment of writing it on the table, it just parses the data on the fly and write the text on the cell. This together with the pagination feature that was added before makes it a lot less memory hungry, and makes …
> Refactor tables

- Dockerfile
Custom templates are not needed right now. But we might again in the future, so I left the code in there commented out.
> fixed Dockerfile to use Godot 3.5.1 stable and not use custom templates

- src/components/dashboard/widget_heatmap/widget_heatmap.gd
- src/components/shared/richtext_uniwidth_resize.gd
Note that i also changed checking the size with `bbcode_text` to `text`, because using `bbcode_text` size also takes into account the size of the bbcode blocks... For example now looks like this:
previously it looked like this:
> Fix setting the tooltip width automatically

- src/components/dashboard/dashboard_container.gd
- src/components/dashboard/dashboard_manager.gd
This extra parameter caused the connection between `dashboard_changed` signal and `save_dashboard` function to fail.
> Remove unnecesary parameter in save_dashboard()

- src/components/dashboard/data_sources/data_source_time_series.gd
For some reason escaping the whole query doesn't work. It only works if we escape/remove the spaces though, so that's what this PR does.
> Remove spaces from instant tsdb query

- src/Main.tscn
- src/assets/theme/dark_theme.tres
- src/components/dashboard/dashboard_container.gd
- src/components/dashboard/dashboard_container.tscn
- src/components/dashboard/data_sources/data_source_two_entry_aggregate.gd
- src/components/dashboard/new_widget_popup/new_widget_popup.gd
- src/components/dashboard/new_widget_popup/new_widget_popup.tscn
- src/components/elements/styled/custom_dragable_window_panel.gd
- src/components/elements/styled/custom_dragable_window_panel.tscn
- src/components/popups/popup_connect.gd
- src/components/popups/popup_generic_confirm.gd
- src/components/popups/popup_ui_settings.gd
- src/components/terminal/component_terminal.gd
- src/project.godot
- src/scripts/ui_terminal_popup.gd
**In this PR**
- Fix for Resh Lite Popup stealing focus (will now only do this when the mouse is over the popup).
- Removed a debug print from the two entries aggregate data source.
- Certain Popups will hide Resh Lite to avoid conflicting input.
- Added a new Window Popup class based on PanelContainer instead of Popup. And changed the "Add/Edit Widget popup" to this new class.
**More detail about the last change:**
The Popup class steals all input as long as it is displayed in exclusive mode. This produced problems with Resh Lite.
As long as the "New Widget" Popup was visible, Resh Lite was not usable. This is a situation where I can imagine having a terminal is especially helpful, so I wanted it to work. The only solution was to move the popup from the Popup class to a "custom" one.
For …
> Fixes to Resh Lite Popup

- src/Main.tscn
- src/components/shared/zoom_elements.gd
- src/components/shared/zoom_group.tscn
- src/components/wizard/wizard_component.tscn
- src/scripts/ui_menu.gd
The zoom button group now is a reusable scene. It will try to stay in the same size indipendent of the ui scale.
As it is hard to make it using a fixed position using Godot UI system, this is the next best thing.
By removing the Godot version number from the main menu (we have it in the About section now anyway) and moving the ui scale to the left in the main hamburger menu, it is a lot more stable in position and scale and allows for more subsequent clicks.
I also added this new scene to the top right of the setup wizard, giving the user an easy way of scaling the UI in the first experience in Resoto UI.
> Improved zoom button group

- src/components/dashboard/widget_table/widget_table_cell.gd
This fixes a bug that caused that scrolling on a table triggered a navigate or copy event.
> Only copy or navigate when clicking

- src/components/dashboard/dashboard_container.gd
This PR just avoids changing dashboards with ALT+Arrow while editing a widget.
> Avoid changing dashboards when editting a widget

- src/components/elements/styled/custom_dragable_window_panel.gd
This PR solves these bugs:
- Resizing the UI when the custom popup was in full screen made it not cover the screen anymore
- Exiting full screen after having made the window smaller than the popup caused some part of the popup to be outside the window
- Add widget dialog full screen was not working properly
> Fix some undesired behaviour in custom popup when pressing full screen

- src/components/dashboard/data_sources/data_source_aggregate_search.gd
- src/components/dashboard/new_widget_popup/data_source_container.gd
- src/components/dashboard/new_widget_popup/data_source_container.tscn
- src/components/dashboard/new_widget_popup/group_variables_element.gd
- src/components/dashboard/new_widget_popup/group_variables_element.tscn
- src/components/dashboard/new_widget_popup/group_variables_widget.gd
- src/components/dashboard/new_widget_popup/group_variables_widget.tscn
- src/data/data_sources_templates.json
This PR redesigns the ui for adding an aggregate data source, and also changes the resulting query label text to something that matches the data-source type:
- Time Series Datasource -> Query
- Search Data Source -> Resoto Search
- The rest of them -> Aggregate Search
> Redesign aggregate search datasource UI

- src/Main.tscn
- src/components/popups/popup_workflows.gd
The workflow popup (upper right corner) still used the old background that is not working correctly with GLES2 anymore.
It also had a problem that it would show the "working" animation, but the workflow was already done.
> Fix Workflows popup

- src/components/elements/styled/custom_dragable_window_panel.gd
- src/components/terminal/component_terminal.gd
- src/scripts/ui_popup_manager.gd
- src/scripts/ui_terminal_manager.gd
- src/scripts/ui_terminal_popup.gd
If they are both opened at the same time, they fight to grab the input and go haywire.
> Fix problem when the Resh Lite popup and Resh Lite component are opened

- src/components/config/component_config.gd
- src/components/config/component_config.tscn
- src/components/config/config_templates/component_config_enum.gd
- src/components/config/config_templates/component_config_template_enum.tscn
Currently the Config Editor crashes when trying to open a benchmark config as it seems the model is still incomplete.
To avoid the Config Editor in crashing the application in such cases, I added a Raw View mode to the Config Editor (available as a Toggle Button at the top which is unlocked if a complete model is found).
When a problem with the model comes up, the Config Editor will automatically open the config in raw mode as a fallback.
> Added raw view to Config Editor and fixed a crash with incomplete model

- src/components/config/config_templates/component_config_complex.gd
It was requested that, even if a config request doesn't return some value that is in the model, we should have that field in the config ui so the user can set it.
> [Config Editor] Use model to add elements that are not in the request response
