- src/components/popups/popup_connect.gd
- src/export_presets.cfg
- src/scripts/autoloads/api_handler.gd
With this PR the UI gets the used protocol via Javascript before connecting.
This will then be used to enabled/disable the use of ssl.
> Enabled SSL detection and usage

- .github/workflows/test-export.yml
Added a workflow that generates a build and uploads it as an artifact.
> Add export workflow for testing builds

- src/components/config/component_config.gd
- src/components/config/config_templates/component_config_line_edit_int.gd
- src/components/dashboard/container/widget_container.gd
- src/components/dashboard/dashboard_container.gd
- src/components/dashboard/dashboard_container.tscn
- src/components/dashboard/dashboard_manager.gd
- src/components/dashboard/data_sources/data_source.gd
- src/components/dashboard/data_sources/data_source_aggregate_search.gd
- src/components/dashboard/data_sources/data_source_text_search.gd
- src/components/dashboard/new_widget_popup/color_condition.gd
- src/components/dashboard/new_widget_popup/data_source_container.gd
- src/components/dashboard/new_widget_popup/new_widget_popup.gd
- src/components/dashboard/shared/base_widget.gd
- src/components/dashboard/widget_heatmap/widget_heatmap.gd
- src/components/dashboard/widget_indicator/color_controller.gd
- src/components/dashboard/widget_table/widget_table.gd
- src/components/elements/styled/custom_dragable_window_popup.gd
- src/components/shared/hex_color_picker.gd
- src/components/shared/int_spinbox_big.gd
- src/components/terminal/component_terminal.gd
- src/scripts/classes/resoto_api.gd
- src/scripts/tools/html_helpers.gd
Mostly unused function parameters missing the `_` prefix or overshadowed variables.
> Fixed a lot of things that produced warnings

- .github/workflows/test-export.yml
Bump to godot 3.5.1, and change build to release mode.
> Updates test-export action

- src/components/dashboard/data_sources/data_source_time_series.gd
- src/components/dashboard/new_widget_popup/data_source_container.gd
- src/components/dashboard/new_widget_popup/filter_widget.gd
- src/components/popups/graph_popup.gd
- src/components/popups/popup_connect.gd
- src/components/shared/int_spinbox_big.tscn
- src/scripts/autoloads/analytics.gd
- src/scripts/classes/resoto_api.gd
- src/scripts/classes/user_agent.gd
This should fix the crash on the test cluster (400 bad response on TSDB endpoint)
> Improved error handling

- src/components/elements/element_tree_map_box.tscn
- src/components/elements/element_treemap.gd
- src/components/node_info/node_info_element.gd
- src/components/node_list/node_list_element.gd
- src/scripts/autoloads/api_handler.gd
- src/scripts/classes/resoto_api.gd
- src/scripts/ui_content.gd
Also fixed a bug on the Node Info using `id()` without putting the id in double quotes (led to crashes)
> Changed default section on the search endpoint to "reported"

- src/components/elements/element_tree_map_box.tscn
- src/components/elements/element_treemap_box.gd
- labels change color depending on the luminance of the background color
- labels change size, padding, etc.
> Improved Treemap charts

- src/components/config/component_config.gd
- src/components/dashboard/data_sources/data_source_aggregate_search.gd
- src/components/dashboard/widget_heatmap/widget_heatmap.gd
- src/components/dashboard/widget_heatmap/widget_heatmap.tscn
Also gives more feedback for the user how to solve this.
In this PR it will also fix a bug with configurations CTRL+S capturing events when the config is not open!
> Fixed a crash in the Heatmap when an aggregation does not have two axis.

- src/components/config/component_config.tscn
- src/components/dashboard/new_widget_popup/data_source_container.gd
- src/components/dashboard/widget_heatmap/widget_heatmap.gd
- src/components/dashboard/widget_heatmap/widget_heatmap.tscn
- src/components/dashboard/widget_table/widget_table.gd
- Improved the initial look on the Add Widget dialogue
- Fixed some visual glitches
- Added a better/new tooltip
> Fixed more potential crash issues on the heatmap

- src/components/dashboard/dashboard_container.tscn
- src/components/dashboard/new_widget_popup/new_widget_popup.gd
- src/components/dashboard/widget_chart/widget_chart.gd
- src/components/dashboard/widget_chart/widget_chart.tscn
- I also optimized the way that labels are added to the mouseover as it wasn't very effective for a process function.
- Fixed a critical bug in the "Add Widget" popup. Changing a widget type while a data source was selected could lead to an invisible "Add Data Source" button.
> Improvements to Chart Widget (Added time at x axis tooltip) and fixes

- src/components/dashboard/new_widget_popup/new_widget_popup.gd
Duplicated widgets are now created with the correct widget type.
> Fixed a bug in widget duplication

- src/components/dashboard/widget_chart/widget_chart.gd
- src/components/dashboard/widget_chart/widget_chart.tscn
- src/components/dashboard/widget_chart/widget_chart_serie.gd
- src/components/shared/combo_box.gd
This pr makes an offset in the grid so that always the 0 is clearly visible.
> Make 0 always visible in Line charts if the y axis has negative values.

- src/components/dashboard/dashboard_container.gd
- src/components/dashboard/dashboard_manager.gd
- src/scripts/classes/utils.gd
Also added a Util function to save a string as a json and used that to locally save exported dashboards.
> Fixed bug in Dashboard Tabs

- src/components/node_info/node_info_element.gd
Fixed a bug where maximizing and minimizing the All Data field woul lead to a crash
> Fixed All Data max/min bug

- src/scripts/classes/resoto_api.gd
While the error is just a message in Godot, ... it's annoying...
> Fix JSON parse error in API

- src/Main.tscn
- src/assets/icons/icon_128_search.svg.import
- src/project.godot
- src/scripts/ui_menu.gd
- Removes Documentation button and replaces it with smaller version
- Fixed the wrong tooltips of buttons
- Added the zoom scale as a label between the zoom buttons
> Improvements to the bottom menu

- src/components/node_info/node_info_element.gd
- src/components/shared/graph_a_star.tscn
- src/project.godot
- src/scripts/classes/graph_a_star.gd
Breadcrumbs in explore view didn't show the shortest path to root but just any path to root. This is solved by using Godot AStar class.
> Fixes Breadcrumb in explore view

- src/components/dashboard/widget_chart/widget_chart.gd
- src/components/dashboard/widget_chart/widget_chart.tscn
- src/components/dashboard/widget_chart/widget_chart_serie.gd
- src/components/dashboard/widget_chart/widget_chart_serie.tscn
1. Fix YLabels not being displayed sometimes when min value is not 0
2. Catch some division by 0 errors
3. Fix range of auto-scale when max and min values were too close between each other
> Some fixes to Line Chart

- src/components/collect_run_display/collect_run_display.gd
- src/components/wizard/setup_wizard_component.gd
- src/components/wizard/wizard_steps/custom_steps/wizard_step_custom_collect_run_status.gd
- src/scripts/autoloads/analytics.gd
Added some events, if more are needed, I can add them here before merging.
> Add analytics events for Setup Wizard

- src/components/dashboard/new_widget_popup/new_widget_popup.gd
- src/components/dashboard/new_widget_popup/new_widget_popup.tscn
Added a small "alert" telling the user if global Dashboard filters are active when editing / adding a widget.
> Added a "Global Filter" alert to the Add/Edit widget popup

- src/assets/generic/spin_shader.tres
- src/components/collect_run_display/collect_run_display_progress_element.tscn
- src/components/dashboard/dashboard_container.gd
- src/components/dashboard/dashboard_container_placeholder.tscn
- src/components/dashboard/dashboard_manager.gd
- src/components/toast/component_toast_manager.gd
- src/components/toast/toast_component_manager.tscn
- src/scripts/autoloads/global.gd
Also introduces the global signal `toast_show_saved` that can be used to display a small save icon.
> Fix excessive dashboard saving and saving bugs

- src/assets/theme/dark_theme.tres
- src/components/dashboard/data_sources/data_source.gd
- src/components/dashboard/data_sources/data_source_aggregate_search.gd
- src/components/dashboard/data_sources/data_source_text_search.gd
- src/components/dashboard/data_sources/data_source_time_series.gd
- src/components/dashboard/new_widget_popup/data_source_container.gd
- src/components/dashboard/new_widget_popup/data_source_container.tscn
- src/components/dashboard/new_widget_popup/filter_widget.tscn
- src/components/dashboard/widget_chart/widget_chart.gd
- src/components/dashboard/widget_chart/widget_chart_serie.gd
- src/components/dashboard/widget_heatmap/widget_heatmap.gd
- src/components/shared/combo_box.gd
- src/components/shared/combo_box.tscn
- src/components/shared/icon_tooltip_helper.gd
- src/components/shared/icon_tooltip_helper.tscn
- src/components/shared/richtext_uniwidth_resize.gd
Fixed a bug in the Heatmap when trying to use a float for an axis
Added a lot of help texts and examples
Added links to the docs where relevant
Showing available labels of a Time Series response
> Redesigned Data Sources in the Data Source Container

- src/data/resoto_example_dashboard.json
> Update example dashboard

- src/components/dashboard/data_sources/data_source_time_series.gd
- src/scripts/classes/user_agent.gd
Related to this:
https://github.com/someengineering/resoto/pull/1284
> Added better error handling and fixed a crash with new Error codes

- src/components/dashboard/widget_table/widget_table.tscn
- src/scripts/ui_terminal_popup.gd
This PR also includes a small fix for the Resh Lite popup default position
> Move pagination to align right

- src/components/config/component_config.gd
- src/components/config/config_templates/component_config_array_element.gd
- src/components/config/config_templates/component_config_custom_config.gd
- src/components/config/config_templates/component_config_template_custom_config.tscn
I also improved the way that raw json display is handled in the config editor when the json has an error.
> Fixed incorrect handling of arrays in the config editor

- src/components/dashboard/container/widget_container.gd
- src/components/dashboard/container/widget_container.tscn
- src/components/dashboard/data_sources/data_source.gd
- src/components/dashboard/data_sources/data_source_aggregate_search.gd
- src/components/dashboard/data_sources/data_source_text_search.gd
- src/components/dashboard/data_sources/data_source_time_series.gd
- src/components/dashboard/new_widget_popup/new_widget_popup.gd
- src/components/dashboard/shared/loading_overlay.tscn
It shows the little spinning thing.
> Add loading overlay when a widget is waiting to get data from a query

- src/components/popups/popup_ui_settings.gd
- src/components/popups/popup_ui_settings.tscn
> Add github link to the about section

- .github/workflows/pypi.yml
- resotoui/MANIFEST.in
- resotoui/README.md
- resotoui/resotoui/__init__.py
- resotoui/resotoui/ui/readme.txt
- resotoui/setup.py
This should build the UI, copy it to the python package directory, build the package and on a tag upload it to PyPI.
> Initial commit resotoui Python package

- src/components/terminal/component_terminal.gd
> Display meaningful parse errors in Resh Lite.

- src/components/popups/browser_warning_popup.gd
- src/components/popups/browser_warning_popup.tscn
- src/scripts/autoloads/global.gd
- src/scripts/ui_main.gd
- src/ui/main_app_popups.tscn
> Adding a warning when using non-Chrome browser

- src/components/dashboard/container/widget_container.gd
> Added an error message when no Data Source is configured on a widget.

- src/components/job_editor/job_editor_component.gd
- src/components/job_editor/job_editor_element.gd
- src/components/job_editor/job_editor_element.tscn
- New Jobs are created as deactivated
- Examples should now work
- Four new Examples added
- Cron Expression regex check is hidden until we can fix it.
- Default Schedule set to `0 * * * *`
- Default Event set to `cleanup_plan`
> Fixes for the Job UI

- src/components/dashboard/widget_world_map/widget_world_map.gd
- src/components/dashboard/widget_world_map/widget_world_map.tscn
- src/components/dashboard/widget_world_map/widget_world_map_column.gd
This PR includes:
- Wrap angle when auto-rotating
- Add clear button in the combo box
- Map zooms to mouse in 2d now
- Change default low color to something not similar than the ocean blue
> Fixes to the world map

- src/assets/icons/icon_128_logout.svg
- src/assets/icons/icon_128_logout.svg.import
- src/scripts/ui_menu.gd
- src/ui/main_app_menu.tscn
> Add logout button

- src/components/node_info/node_info_element.gd
The problem trigger when you run the native version.
> Minor fix: Method instead attribute
